export const DASHBOARD_TAB_ADD = 'DASHBOARD_TAB_ADD';
export const DASHBOARD_TAB_DELETE = 'DASHBOARD_TAB_DELETE';
export const DASHBOARD_TAB_EDIT = 'DASHBOARD_TAB_EDIT';

export const DASHBOARD_WIDGET_ADD = 'DASHBOARD_WIDGET_ADD';
export const DASHBOARD_WIDGET_DELETE = 'DASHBOARD_WIDGET_DELETE';
export const DASHBOARD_WIDGET_EDIT = 'DASHBOARD_WIDGET_EDIT';
